### ISSUE TITLE
A bug for running pschism_COSINE using new io

### ISSUE THREAD

**Issue by ZhenlinZhang** [schism-dev/schism#66] opened 2022-05-05 00:43 UTC
Running  pschism_COSINE resulted in an error in:
schism_step.F90, Line 9564: 'STEP: icount>nscribes(2.9)' 
And this error is caused by the following: 
in schism_ini.F90 Line 6767, do i=i,ntr(6), I think that it should be ntr(8), because ntr(6) corresponds to ECO.

**Comment by josephzhang8** [comment] 2022-05-05 00:55
Thx Zhenlin! I've pushed the fix.


-Joseph

Joseph Zhang
Office: (804) 684 7466
Web: schism.wiki

From: ZhenlinZhang ***@***.***>
Sent: Wednesday, May 4, 2022 8:44 PM
To: schism-dev/schism ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [schism-dev/schism] A bug for running pschism_COSINE using new io (Issue #66)


[EXTERNAL to VIMS received message]


Running pschism_COSINE resulted in an error in:
schism_step.F90, Line 9564: 'STEP: icount>nscribes(2.9)'
And this error is caused by the following:
in schism_ini.F90 Line 6767, do i=i,ntr(6), I think that it should be ntr(8), because ntr(6) corresponds to ECO.

-

**Comment by jamal919** [comment] 2022-05-05 15:46
Fixed in 98f3ad0add3db4258e04bb0cad6964c896e4a8f2

**Closed by jamal919** 2022-05-05 15:46 UTC
